name: Publish wheels

on:
  push:
    tags:
      - v*
  pull_request:
    paths:
      - 'Cargo.toml'
      - 'pyproject.toml'

jobs:
  build:
    # This workflow comes from https://github.com/pydantic/pydantic-core/blob/main/.github/workflows/ci.yml
    name: build on ${{ matrix.os }} (${{ matrix.target }} - ${{ matrix.manylinux }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            ls: dir
            target: x86_64
            manylinux: auto
            python-architecture: x64
            interpreter: 3.7 3.8 3.9 3.10 3.11
          - os: windows
            ls: dir
            target: i686
            manylinux: auto
            python-architecture: x86
            interpreter: 3.7 3.8 3.9 3.10 3.11
          - os: macos
            target: x86_64
            manylinux: auto
            python-architecture: x64
            interpreter: 3.7 3.8 3.9 3.10 3.11 pypy3.7 pypy3.8 pypy3.9
          - os: macos
            target: aarch64
            manylinux: auto
            python-architecture: x64
            interpreter: 3.7 3.8 3.9 3.10 3.11
          # Build all manylinux targets on 2_24
          # https://github.com/pypa/manylinux#readme
          # https://github.com/PyO3/maturin-action/blob/135c746/src/index.ts#L33
          - os: ubuntu
            target: x86_64
            manylinux: 2_24
            python-architecture: x64
            interpreter: 3.7 3.8 3.9 3.10 3.11 pypy3.7 pypy3.8 pypy3.9
          - os: ubuntu
            target: aarch64
            manylinux: 2_24
            python-architecture: x64
            interpreter: 3.7 3.8 3.9 3.10 3.11 pypy3.7 pypy3.8 pypy3.9
          - os: ubuntu
            target: i686
            manylinux: 2_24
            python-architecture: x64
            interpreter: 3.7 3.8 3.9 3.10 3.11 pypy3.7 pypy3.8 pypy3.9
          - os: ubuntu
            target: armv7
            manylinux: 2_24
            python-architecture: x64
            interpreter: 3.7 3.8 3.9 3.10 3.11
          - os: ubuntu
            target: ppc64le
            manylinux: 2_24
            python-architecture: x64
            interpreter: 3.7 3.8 3.9 3.10 3.11
          - os: ubuntu
            target: s390x
            manylinux: 2_24
            python-architecture: x64
            interpreter: 3.7 3.8 3.9 3.10 3.11
          # musllinux - https://musl.libc.org/about.html
          - os: ubuntu
            target: x86_64
            manylinux: musllinux_1_1 # /!\ value used in steps conditions below.
            python-architecture: x64
            interpreter: 3.7 3.8 3.9 3.10 3.11 pypy3.7 pypy3.8 pypy3.9
          - os: ubuntu
            target: aarch64
            manylinux: musllinux_1_1
            python-architecture: x64
            interpreter: 3.7 3.8 3.9 3.10 3.11 pypy3.7 pypy3.8 pypy3.9

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: ${{ matrix.python-architecture }}

      - run: pip install -U twine

      - name: build sdist
        if: ${{ matrix.os == 'ubuntu' && matrix.target == 'x86_64' && matrix.manylinux != 'musllinux_1_1' }}
        uses: messense/maturin-action@v1
        with:
          command: sdist
          args: --out dist/
          rust-toolchain: stable

      - name: build wheels
        uses: messense/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: ${{ matrix.manylinux }}
          args: --release --out dist/ --interpreter ${{ matrix.interpreter }}
          rust-toolchain: stable

      - run: ${{ matrix.ls || 'ls -lh' }} dist/

      - run: twine check --strict dist/*

      - name: install built wheel
        if: ${{ matrix.os == 'ubuntu' && matrix.target == 'x86_64' && matrix.manylinux != 'musllinux_1_1' }}
        run: |
          pip install canonicaljson-rs --no-index --find-links dist/ --force-reinstall
          python -c "import canonicaljson"

      - uses: actions/upload-artifact@v3
        with:
          name: pypi_files
          path: dist/
